services:
  - type: web
    name: learning-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 3 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
